apiVersion: v1
kind: PersistentVolume
metadata:
  name: opt-senzing-volume
  labels:
    type: local
  namespace: ${DEMO_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 40Gi
  hostPath:
    path: /opt/senzing
  storageClassName: manual
