apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2-data-stor-volume
  labels:
    assign-to: "data-stor"
  namespace: ${DEMO_NAMESPACE}
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/db2/data-stor"
