kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-volume
  labels:
    type: local
  namespace: ${K8S_NAMESPACE_NAME}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/postgresql"
