apiVersion: v1
kind: PersistentVolume
metadata:
  name: opt-senzing-volume
  labels:
    type: local
  namespace: ${DEMO_NAMESPACE}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/senzing"
